---
name: CI to DOcker Hub

on: 
  push:
    branches:
      - master

jobs:


  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: install required packages
      run: sudo apt-get install -f curl

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./python
        file: ./python/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: rum python docker image
      run: docker run -d --rm  --name python_flask -p 5000:5000  gilesfa/python:latest

    - name: exec http://127.0.0.1:5000
      run: curl 127.0.0.1:5000

    # - name: docker build python
    #   run: docker build ./python  -t gilesfa/python:latest

    # - name: push python image to docker hub
    #   run: docker push gilesfa/python:latest