---
name: CI-Docker build

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker build python
      run: docker build ./python aimvector/python:1.0.0