---
name: CI-Docker build

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker build python
      run: docker build ./python  -t gilesfa/python:latest

    - name: push python image to docker hub
      run: docker push gilesfa/python:latest
